float32 d_v_angle_v
float32 d_v_angle_z
float32 v_angle_v
float32 v_angle_z
float32 los_angle_v 
float32 los_angle_z
float32 diff_los_angle_v
float32 diff_los_angle_z
float32 ex
float32 ey
float32 yaw
float32 pitch
float32 roll


# 用于画图 (c) - 像素坐标
float32 pixel_u
float32 pixel_v

# 用于画图 (d) - 加速度
float32 acc_normal      # 法向加速度

# 用于画图 (e) - 速度
float32 vel_total       # 合速度大小 ||V||
float32 vel_normal      # 法向速度 Vn